# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# IP: ip/TX_RX/TX_RX.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TX_RX || ORIG_REF_NAME==TX_RX} -quiet] -quiet
