set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/FMSC/loopback_testv/loopback_test.srcs/sources_1/ip/TX_RX/TX_RX/TX_RX_in_context.xdc rfile:../../../loopback_test.srcs/sources_1/ip/TX_RX/TX_RX/TX_RX_in_context.xdc id:1 order:EARLY scoped_inst:TX_RXex/TX_RX_support_i} [current_design]
set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/FMSC/loopback_testv/loopback_test.srcs/constrs_1/new/const.xdc rfile:../../../loopback_test.srcs/constrs_1/new/const.xdc id:2} [current_design]
current_instance TX_RXex/TX_RX_support_i
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.334 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.334 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11 [get_ports  GTP_CLK_P]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports  GTP_CLK_N]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7  [get_ports  txp ]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7  [get_ports  txn ]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14  [get_ports  rxp ]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14  [get_ports  rxn ]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA4 [get_ports  DRP_CLK_IN_P]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB4 [get_ports  DRP_CLK_IN_N]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J8 [get_ports reset]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN G6 [get_ports sfp_dis0]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN K8 [get_ports sfp_dis1]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells TX_RX_support_i/inst/TX_RX_init_i/TX_RX_i/gt0_TX_RX_i/gtpe2_i]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y5 [get_cells TX_RX_support_i/inst/TX_RX_init_i/TX_RX_i/gt1_TX_RX_i/gtpe2_i]
